name: Gatsby deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: git config --global user.email "pep@rodeja.me"
    - run: git config --global user.name "Github CI"
    - run: npm run ci-deploy
      env: # Or as an environment variable
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
